#!/usr/bin/env bash
# =============================================================================
# audit_v162_operator_procedures.sh — every procedure the public guides teach,
# executed end to end before it is published.
#
# The point is not to test the protocol again. It is that no command reaches a
# miner's terminal unless it ran here first, exactly as written, against the
# v16.2.2 binaries — including the NODE_BIND / heartbeat path, which only
# exists after the V16 activation and therefore needs a devnet whose activation
# height is low enough to cross.
#
# Throwaway wallets, throwaway credentials, a throwaway chain. Nothing here
# reads a real wallet, and no command below puts a secret in argv.
#
#   Env: BIN (mainnet build, for --help/flag checks)
#        DEVNET (devnet build used to actually run a chain; must have the V16
#                activation low — build-devnet-v2e)
# =============================================================================
set -Euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="${BIN:-/home/sost/SOST/sostcore/rel-v1622-a/build}"
DEVNET="${DEVNET:-/home/sost/SOST/sostcore/rel-v162-a/build-devnet-v2e}"
W="$(mktemp -d /tmp/v162ops.XXXXXX)"
P2P=$(( (RANDOM % 9000) + 45000 )); RPC=$(( P2P + 1 ))
PASS=0; FAIL=0
ok(){  printf '  [PASS] %s\n' "$*"; PASS=$((PASS+1)); }
bad(){ printf '  [FAIL] %s\n' "$*"; FAIL=$((FAIL+1)); }
sect(){ printf '\n=== %s ===\n' "$*"; }
NODE_PID=""
cleanup(){ [[ -n "$NODE_PID" ]] && kill "$NODE_PID" 2>/dev/null; wait 2>/dev/null; true; }
trap cleanup EXIT
for f in "$BIN/sost-cli" "$DEVNET/sost-node" "$DEVNET/sost-miner" "$DEVNET/sost-cli"; do
  [[ -x "$f" ]] || { echo "FATAL missing $f"; exit 1; }
done
echo "mainnet binaries : $(sha256sum "$BIN/sost-cli" | cut -c1-24) (cli)"
echo "devnet harness   : $DEVNET"

sect "1. every flag the guides use exists in v16.2.2 --help"
check_flag(){ # check_flag <binary> <flag>
  # --help exits non-zero on some binaries, and under `set -o pipefail` that
  # fails the whole pipeline no matter what grep found. Capture, then search.
  local out; out="$("$BIN/$1" --help 2>&1 || true)"
  case "$out" in
    *"$2"*) ok "$1 $2" ;;
    *) bad "$1 $2 — NOT in --help, do not publish it" ;;
  esac
}
check_flag sost-node  --rpc-pass-file
check_flag sost-node  --node-key-file
check_flag sost-node  --p2p-enc
check_flag sost-miner --rpc-pass-file
check_flag sost-miner --rpc-pass-fd
check_flag sost-miner --wallet-passphrase-file
check_flag sost-miner --mining-key-label
check_flag sost-cli   --rpc-pass-file
check_flag sost-cli   wallet-export
check_flag sost-cli   wallet-import
check_flag sost-cli   --mining-key-label
"$BIN/sost-cli" --wallet "$W/probe.json" newwallet >/dev/null 2>&1
BINDUSAGE="$("$BIN/sost-cli" --wallet "$W/probe.json" createnodebind 2>&1 || true)"
case "$BINDUSAGE" in
  *--node-key-file*) ok "sost-cli createnodebind --node-key-file (usage confirms it)" ;;
  *) bad "createnodebind usage does not mention --node-key-file" ;;
esac

sect "2. NEW OPERATOR — wallet, node, miner, balance (as the guide says it)"
umask 077
"$BIN/sost-cli" --wallet "$W/wallet.json" newwallet > "$W/new.log" 2>&1
# A real operator labels the mining key; the guides must work for a label that
# is NOT "default", because createnodebind used to assume that one.
LABEL="mi-minero-01"
"$BIN/sost-cli" --wallet "$W/wallet.json" getnewaddress "$LABEL" > "$W/label.log" 2>&1
ADDR=$(grep -oE 'sost1[a-z0-9]+' "$W/label.log" | head -1)
[[ -n "$ADDR" ]] && ok "newwallet creates a wallet and an address" || bad "newwallet failed"
[[ "$(stat -c %a "$W/wallet.json")" == "600" ]] && ok "the wallet file is created mode 600" \
  || bad "wallet file is mode $(stat -c %a "$W/wallet.json") — the guide must say chmod 600"

# The RPC password: generated by the operator, stored in a private file.
openssl rand -base64 30 | tr -d '\n' > "$W/rpc.pass"; printf '\n' >> "$W/rpc.pass"
chmod 600 "$W/rpc.pass"
[[ "$(stat -c %a "$W/rpc.pass")" == "600" ]] && ok "the RPC password file is mode 600" || bad "wrong mode on rpc.pass"

"$DEVNET/sost-node" --profile dev --genesis "$ROOT/genesis_block.json" --chain "$W/chain.json" \
  --port "$P2P" --rpc-port "$RPC" --rpc-user sostuser --rpc-pass-file "$W/rpc.pass" \
  --connect 127.0.0.1:1 >"$W/node.log" 2>&1 &
NODE_PID=$!
rpc(){ curl -s --max-time 15 -u "sostuser:$(cat "$W/rpc.pass")" -H 'content-type: application/json' \
        --data "{\"method\":\"$1\",\"params\":${2:-[]},\"id\":1}" "http://127.0.0.1:$RPC/"; }
hgt(){ rpc getblockcount | python3 -c 'import sys,json
try: print(json.load(sys.stdin)["result"])
except Exception: print("")'; }
for _ in $(seq 1 30); do sleep 1; [[ -n "$(hgt)" ]] && break; done
[[ -n "$(hgt)" ]] && ok "the node starts with --rpc-pass-file (no password in argv)" || { bad "node did not start"; exit 1; }
tr '\0' ' ' < "/proc/$NODE_PID/cmdline" | grep -qF "$(cat "$W/rpc.pass")" \
  && bad "the node has the password in argv" || ok "...confirmed: nothing secret in the node's argv"

"$DEVNET/sost-miner" --profile dev --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/rpc.pass" --wallet "$W/wallet.json" --mining-key-label "$LABEL" \
  --blocks 3 --threads 3 >"$W/miner.log" 2>&1
grep -qc "submitted to node OK" "$W/miner.log" && ok "the miner mines with --wallet + --mining-key-label (SbPoW identity)" \
                                               || bad "the documented miner command did not mine"
MINED=$(grep -c "submitted to node OK" "$W/miner.log")
[[ "$MINED" -ge 1 ]] && ok "blocks accepted: $MINED" || bad "no block accepted"

"$BIN/sost-cli" --wallet "$W/wallet.json" --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/rpc.pass" getbalance "$ADDR" > "$W/bal.log" 2>&1
grep -qE "SOST" "$W/bal.log" && ok "getbalance answers through --rpc-pass-file" || { bad "getbalance failed"; head -3 "$W/bal.log"; }
grep -qE "Immature|Spendable" "$W/bal.log" && ok "...and separates spendable from immature (coinbase maturity)" \
                                            || bad "balance does not show maturity"
"$BIN/sost-cli" --wallet "$W/wallet.json" --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/rpc.pass" listunspent "$ADDR" > "$W/lu.log" 2>&1
grep -q "ON-CHAIN UTXOs" "$W/lu.log" && ok "listunspent reads the chain, not the local cache" || bad "listunspent did not query the chain"

sect "3. the 401 an operator will actually hit"
printf 'la-contrasena-equivocada\n' > "$W/bad.pass"; chmod 600 "$W/bad.pass"
timeout 120 "$DEVNET/sost-miner" --profile dev --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/bad.pass" --wallet "$W/wallet.json" --mining-key-label "$LABEL" \
  --blocks 1 --threads 2 >"$W/m401.log" 2>&1 || true
grep -q "RPC AUTHENTICATION REJECTED" "$W/m401.log" \
  && ok "a wrong RPC password is named as an authentication failure (the guide's 401 section)" \
  || bad "the 401 is not explained to the operator"

sect "4. wallet v1 keeps working; v2 is optional and preserves the identity"
printf 'una-frase-de-paso-larga-de-prueba\n' > "$W/pp"; chmod 600 "$W/pp"
"$BIN/sost-cli" --wallet "$W/wallet.json" wallet-export --encrypted \
  --output "$W/wallet.v2.json" --passphrase-fd 9 9<"$W/pp" >"$W/exp.log" 2>&1
python3 -c "import json,sys;d=json.load(open('$W/wallet.v2.json'));sys.exit(0 if d.get('version')==2 else 1)" \
  && ok "wallet-export --passphrase-fd writes a v2 (encrypted) copy — the v1 file is untouched" \
  || bad "wallet-export failed"
[[ -s "$W/wallet.json" ]] && ok "...and the original v1 wallet still exists (no overwrite in the procedure)" \
                          || bad "the original wallet was destroyed"
# recovery drill: import the backup into a SEPARATE wallet and compare addresses
"$BIN/sost-cli" --wallet "$W/restore.json" newwallet >/dev/null 2>&1
"$BIN/sost-cli" --wallet "$W/restore.json" wallet-import --encrypted \
  --input "$W/wallet.v2.json" --passphrase-fd 9 9<"$W/pp" >"$W/imp.log" 2>&1
diff <("$BIN/sost-cli" --wallet "$W/wallet.json" listaddresses 2>/dev/null) \
     <("$BIN/sost-cli" --wallet "$W/restore.json" listaddresses 2>/dev/null) >/dev/null \
  && ok "the recovery drill restores the SAME addresses (the guide's verification step)" \
  || bad "restored wallet has different addresses"
"$DEVNET/sost-miner" --profile dev --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/rpc.pass" --wallet "$W/wallet.v2.json" --mining-key-label "$LABEL" \
  --wallet-passphrase-file "$W/pp" --blocks 1 --threads 3 >"$W/m_v2.log" 2>&1
V2ADDR=$(grep -oE 'sost1[a-z0-9]{20,}' "$W/m_v2.log" | head -1)
[[ "$V2ADDR" == "$ADDR" ]] && ok "mining with the ENCRYPTED wallet pays the SAME address ($ADDR)" \
                           || bad "the address changed: $ADDR -> $V2ADDR"

sect "5. NODE_BIND, heartbeat and eligibility (only valid after activation)"
# This devnet activates V16 low enough to cross, which is the only way to run
# the procedure the guide describes for #30,000 onward.
H=$(hgt); ACT=$(rpc getblockchaininfo | grep -oE '"hist_jackpot_v2_height":[0-9]+' | grep -oE '[0-9]+' || true)
echo "  devnet height $H, V16 activation at ${ACT:-18}"
"$DEVNET/sost-miner" --profile dev --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/rpc.pass" --wallet "$W/wallet.json" --mining-key-label "$LABEL" \
  --blocks 20 --threads 3 >>"$W/miner.log" 2>&1 || true
H=$(hgt); echo "  mined up to height $H"

openssl rand -hex 32 > "$W/node.key"; chmod 600 "$W/node.key"
# Built with the RELEASE cli (the devnet harness carries an older one); a
# NODE_BIND is network-independent bytes, so the node accepts it either way.
BIND=$("$BIN/sost-cli" --wallet "$W/wallet.json" --mining-key-label "$LABEL" \
        createnodebind 1 --node-key-file "$W/node.key" 2>"$W/bind.err" | tr -d '[:space:]')
[[ ${#BIND} -eq 352 ]] && ok "createnodebind builds the 176-byte NODE_BIND from a mode-600 key file" \
                       || { bad "createnodebind failed"; head -2 "$W/bind.err"; }
grep -qi "visible to any local user" "$W/bind.err" \
  && bad "createnodebind warned about argv exposure" \
  || ok "...and no key touched the command line (it names the mining key it bound)"
SEND=$(rpc sendrawtransaction "[\"$BIND\"]")
echo "$SEND" | grep -qE '"result"' && ok "the node accepts the NODE_BIND transaction" \
                                   || { bad "NODE_BIND rejected: $(echo "$SEND" | head -c 120)"; }
"$DEVNET/sost-miner" --profile dev --rpc "127.0.0.1:$RPC" --rpc-user sostuser \
  --rpc-pass-file "$W/rpc.pass" --wallet "$W/wallet.json" --mining-key-label "$LABEL" \
  --blocks 2 --threads 3 >>"$W/miner.log" 2>&1 || true
ELIG=$(rpc checkhistoricaljackpoteligibility "[\"$ADDR\"]")
echo "$ELIG" | grep -qE '"result"' && ok "checkhistoricaljackpoteligibility answers for the address" \
                                   || bad "eligibility RPC failed: $(echo "$ELIG" | head -c 120)"
echo "  eligibility: $(echo "$ELIG" | head -c 200)"

sect "6. restart — the operator's normal stop/start"
TIP_BEFORE=$(hgt)
kill "$NODE_PID"; wait "$NODE_PID" 2>/dev/null; NODE_PID=""
"$DEVNET/sost-node" --profile dev --genesis "$ROOT/genesis_block.json" --chain "$W/chain.json" \
  --port "$P2P" --rpc-port "$RPC" --rpc-user sostuser --rpc-pass-file "$W/rpc.pass" \
  --connect 127.0.0.1:1 >>"$W/node.log" 2>&1 &
NODE_PID=$!
for _ in $(seq 1 40); do sleep 1; [[ -n "$(hgt)" ]] && break; done
[[ "$(hgt)" == "$TIP_BEFORE" ]] && ok "the node restarts at the same height ($TIP_BEFORE) — no reindex" \
                                || bad "height changed on restart: $TIP_BEFORE -> $(hgt)"

sect "7. no secret anywhere it should not be"
SECRET=$(cat "$W/rpc.pass")
grep -qF "$SECRET" "$W/node.log" "$W/miner.log" "$W/bal.log" "$W/lu.log" 2>/dev/null \
  && bad "the RPC password appears in a log" || ok "the RPC password appears in no log"
grep -qF "$(cat "$W/pp")" "$W"/*.log 2>/dev/null \
  && bad "the wallet passphrase appears in a log" || ok "the wallet passphrase appears in no log"
grep -qF "$(cat "$W/node.key")" "$W"/*.log 2>/dev/null \
  && bad "the node key appears in a log" || ok "the node key appears in no log"

printf '\n=== %d passed, %d failed ===\n' "$PASS" "$FAIL"
echo "logs: $W"
[[ $FAIL -eq 0 ]] || exit 1
