#!/usr/bin/env bash
#
# install-sost-node.sh — install or repair the sost-node systemd service.
#
# Idempotent. Safe to re-run. Will NOT overwrite existing RPC credentials
# unless --regen-creds is passed.
#
# What it does:
#   1. Ensures /etc/sost exists with mode 700, owned by root.
#   2. If /etc/sost/rpc.env is missing OR empty, generates two 40-char
#      hex tokens (openssl rand -hex 20) and writes them as RPC_USER /
#      RPC_PASS. File mode 600.
#   3. Copies the systemd unit template to /etc/systemd/system/sost-node.service.
#   4. systemctl daemon-reload + enable --now sost-node.
#   5. Runs the healthcheck and prints PASS/FAIL.
#
# Run as root.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/sost-node.service.template"
HEALTHCHECK="${SCRIPT_DIR}/healthcheck.sh"
UNIT_DEST="/etc/systemd/system/sost-node.service"
ENV_DIR="/etc/sost"
ENV_FILE="${ENV_DIR}/rpc.env"

REGEN_CREDS=0
for arg in "$@"; do
  case "$arg" in
    --regen-creds) REGEN_CREDS=1 ;;
    --help|-h)
      cat <<EOF
Usage: sudo $0 [--regen-creds]

  --regen-creds   Force-regenerate /etc/sost/rpc.env even if it exists.
                  Requires the miner config to be updated to match.
EOF
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root (use sudo)" >&2
  exit 1
fi

if [ ! -f "$TEMPLATE" ]; then
  echo "template not found: $TEMPLATE" >&2
  exit 1
fi

# ----------------------------------------------------------------- env dir

if [ ! -d "$ENV_DIR" ]; then
  echo "creating $ENV_DIR"
  mkdir -p "$ENV_DIR"
fi
chmod 700 "$ENV_DIR"
chown root:root "$ENV_DIR"

# ----------------------------------------------------------------- env file

needs_regen=0
if [ ! -f "$ENV_FILE" ]; then
  needs_regen=1
elif ! grep -qE '^RPC_USER=.+' "$ENV_FILE" || ! grep -qE '^RPC_PASS=.+' "$ENV_FILE"; then
  needs_regen=1
fi
if [ "$REGEN_CREDS" -eq 1 ]; then
  needs_regen=1
fi

if [ "$needs_regen" -eq 1 ]; then
  echo "generating fresh RPC credentials in $ENV_FILE"
  if ! command -v openssl >/dev/null 2>&1; then
    echo "openssl not found — install with: apt install -y openssl" >&2
    exit 1
  fi
  rpc_user="$(openssl rand -hex 20)"
  rpc_pass="$(openssl rand -hex 20)"
  umask 0177
  cat > "$ENV_FILE" <<EOF
# /etc/sost/rpc.env — RPC credentials for sost-node systemd service.
# 40-char hex tokens generated by openssl rand -hex 20.
# DO NOT COMMIT. DO NOT SHARE. Mode 600, root:root.
RPC_USER=${rpc_user}
RPC_PASS=${rpc_pass}
EOF
  umask 0022
  chmod 600 "$ENV_FILE"
  chown root:root "$ENV_FILE"
  echo "  RPC_USER prefix: ${rpc_user:0:8}... (40 chars)"
  echo "  RPC_PASS prefix: ${rpc_pass:0:8}... (40 chars)"
  echo
  echo "  IMPORTANT: copy these to your miner host so the miner uses the SAME values:"
  echo "    ssh root@<this-vps-ip> 'cat /etc/sost/rpc.env'"
  echo
else
  echo "credentials already present in $ENV_FILE — keeping them"
  chmod 600 "$ENV_FILE"
  chown root:root "$ENV_FILE"
fi

# ----------------------------------------------------------------- unit

echo "installing systemd unit at $UNIT_DEST"
install -m 0644 -o root -g root "$TEMPLATE" "$UNIT_DEST"

# ----------------------------------------------------------------- restart

echo "reloading systemd and (re)starting sost-node"
systemctl daemon-reload
systemctl enable sost-node >/dev/null 2>&1 || true
systemctl restart sost-node

sleep 3

# ----------------------------------------------------------------- check

if [ -x "$HEALTHCHECK" ]; then
  echo
  "$HEALTHCHECK"
else
  echo
  echo "healthcheck script not executable; running quick smoke:"
  systemctl is-active sost-node >/dev/null && echo "  sost-node: active" \
    || echo "  sost-node: NOT ACTIVE — check journalctl -u sost-node"
fi

echo
echo "Done. To rotate credentials in the future, run with --regen-creds and"
echo "remember to update the miner's --rpc-user / --rpc-pass."
