"""Sprint 5.18c hotfix — SOST address format validators.

The canonical SOST address format is "sost1" + 40 lowercase hex
chars (= 45 total chars). It is defined in
``include/sost/address.h`` (``address_encode``) and produced by
``sost-cli newwallet`` and ``sost-cli getnewaddress``. Earlier
Trinity sprints used a bech32-shaped regex that rejected
legitimate addresses; this hotfix aligns Trinity with the
canonical encoding.

This test file:

1. Accepts the three real-world addresses the operator generated
   via ``sost-cli getnewaddress``.
2. Rejects pre-existing fake addresses that don't match the new
   regex (no leading ``q`` ornament, no characters outside
   ``[0-9a-f]``).
3. Verifies that the centralised validator in
   ``useful_compute_worker_address_map.py`` is the source of
   truth and is imported wherever an address is checked.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts" / "trinity"


def _load(modname: str, path: Path):
    spec = importlib.util.spec_from_file_location(modname, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[modname] = mod
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def addr_mod():
    return _load(
        "ucwam",
        SCRIPTS_DIR / "useful_compute_worker_address_map.py",
    )


# Real addresses generated by sost-cli on the operator's VPS
# (Sprint 5.17 test wallet). They are 45 chars long, "sost1" +
# 40 lowercase hex.
REAL_ADDRESSES = (
    "sost10a262c66d8fdcb45bd21b073b7d8674dac542542",
    "sost14c5281aeaa7f7ca356f5b1b2e76e46ca8409a25e",
    "sost1ca9097d830b74495b95db9d779ad63c90579bc18",
)


@pytest.mark.parametrize("addr", REAL_ADDRESSES)
def test_real_sost_cli_addresses_accepted(addr_mod, addr):
    assert addr_mod.validate_address(addr) is None, (
        f"real sost-cli address {addr!r} rejected"
    )
    assert addr_mod._ADDRESS_RE.match(addr), (
        f"real sost-cli address {addr!r} did not match regex"
    )
    assert len(addr) == 45


def test_address_pattern_exported_constant(addr_mod):
    """The pattern is published as a module-level constant so
    schemas and sibling scripts can reuse it without re-stating
    the regex."""
    assert hasattr(addr_mod, "SOST_ADDRESS_PATTERN")
    assert addr_mod.SOST_ADDRESS_PATTERN == r"^sost1[0-9a-f]{40}$"


# ---------------------------------------------------------------------------
# Negative cases
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("addr,why", [
    ("",                                             "empty"),
    ("sost1",                                        "prefix only"),
    ("sost10a262c66d8fdcb45bd21b073b7d8674dac54254", "truncated by 1 char"),
    ("sost10a262c66d8fdcb45bd21b073b7d8674dac5425421", "one extra char"),
    ("sost10A262C66D8FDCB45BD21B073B7D8674DAC542542", "uppercase hex not allowed"),
    ("SOST10a262c66d8fdcb45bd21b073b7d8674dac542542", "uppercase prefix"),
    ("xost10a262c66d8fdcb45bd21b073b7d8674dac542542", "wrong prefix"),
    ("sost10a262c66d8fdcb45bd21b073b7d8674dac542g42", "non-hex char g"),
    ("sost10a262c66d8fdcb45bd21b073b7d8674dac542 42", "embedded space"),
    ("sost1qaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bech32-shaped, leading q"),
    ("sost1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",   "template placeholder"),
])
def test_invalid_addresses_rejected(addr_mod, addr, why):
    assert addr_mod.validate_address(addr) is not None, (
        f"address {addr!r} should be rejected: {why}"
    )


def test_validate_address_returns_message_string(addr_mod):
    msg = addr_mod.validate_address("xost10a262c66d8fdcb45bd21b0")
    assert isinstance(msg, str)
    assert "payout_address" in msg


# ---------------------------------------------------------------------------
# Consistency across the Trinity payment path
# ---------------------------------------------------------------------------


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def test_payment_proposal_uses_new_regex():
    src = _read(
        SCRIPTS_DIR / "useful_compute_payment_proposal.py"
    )
    assert "^sost1[0-9a-f]{40}$" in src
    # Old bech32-shaped regex must NOT linger anywhere.
    assert "[023456789acdefghjklmnpqrstuvwxyz]" not in src


def test_payment_draft_uses_new_regex():
    src = _read(
        SCRIPTS_DIR / "useful_compute_payment_draft.py"
    )
    assert "^sost1[0-9a-f]{40}$" in src
    assert "[023456789acdefghjklmnpqrstuvwxyz]" not in src


def test_worker_address_map_uses_new_regex():
    src = _read(
        SCRIPTS_DIR / "useful_compute_worker_address_map.py"
    )
    assert "^sost1[0-9a-f]{40}$" in src
    assert "[023456789acdefghjklmnpqrstuvwxyz]" not in src


def test_schemas_use_new_regex():
    for schema_name in (
        "useful_compute_payment_draft.schema.json",
        "useful_compute_payment_proposal.schema.json",
    ):
        p = REPO_ROOT / "schemas" / "trinity" / schema_name
        src = _read(p)
        assert "^sost1[0-9a-f]{40}$" in src, (
            f"{schema_name} did not adopt the new regex"
        )
        assert "[023456789acdefghjklmnpqrstuvwxyz]" not in src
        assert "[0-9a-z]{20,80}" not in src


# ---------------------------------------------------------------------------
# Round-trip with the worker_address_map loader
# ---------------------------------------------------------------------------


def test_address_map_accepts_real_addresses(tmp_path, addr_mod):
    import json
    obj = {
        "schema": addr_mod.SCHEMA_MAP,
        "workers": [
            {
                "worker_id_hash": f"{i:016x}",
                "payout_address": REAL_ADDRESSES[i],
                "label": f"real-worker-{i}",
            }
            for i in range(len(REAL_ADDRESSES))
        ],
    }
    p = tmp_path / "map.json"
    p.write_text(
        json.dumps(obj, sort_keys=True, separators=(",", ":")),
        encoding="utf-8",
    )
    problems = addr_mod.validate_map(obj)
    assert problems == [], f"unexpected problems: {problems}"


def test_address_map_rejects_truncated_real_address(
    tmp_path, addr_mod,
):
    obj = {
        "schema": addr_mod.SCHEMA_MAP,
        "workers": [{
            "worker_id_hash": "0" * 16,
            "payout_address":
                REAL_ADDRESSES[0][:-1],  # drop last hex char
            "label": "truncated",
        }],
    }
    problems = addr_mod.validate_map(obj)
    assert any("payout_address" in p for p in problems), (
        f"truncated address should be rejected; problems={problems}"
    )
