"""Generate human-readable reports from mixer results."""
from datetime import datetime


def build_report(parent_a, parent_b, ranked_candidates):
    """Build a structured report for a mixer run."""
    return {
        "mixer_version": "1.0.0-mvp",
        "generated_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "parent_a": parent_a,
        "parent_b": parent_b,
        "total_candidates": len(ranked_candidates),
        "methods_used": list(set(c.get("method", "") for c in ranked_candidates)),
        "candidates": [
            {
                "rank": c["rank"],
                "formula": c["formula"],
                "method": c["method"],
                "description": c["description"],
                "elements": c["elements"],
                "composite_score": c["composite_score"],
                "scores": c["scores"],
                "why_interesting": _why_interesting(c),
                "risks": _risks(c),
                "recommended_next_step": _next_step(c),
            }
            for c in ranked_candidates
        ],
        "disclaimer": (
            "These are THEORETICAL CANDIDATES generated by heuristic rules. "
            "No DFT calculation, experimental synthesis, or ML property prediction "
            "has been performed. All candidates require independent validation "
            "before any scientific claim can be made."
        ),
    }


def _why_interesting(c):
    """Generate a reason why this candidate might be worth investigating."""
    reasons = []
    scores = c.get("scores", {})
    if scores.get("complexity_score", 0) >= 0.6:
        reasons.append(f"Multi-element composition ({len(c['elements'])} elements) — potentially novel")
    if scores.get("rarity_score", 0) >= 0.7:
        reasons.append(f"Contains rare elements ({scores.get('rarity_label', '')})")
    method = c.get("method", "")
    if method == "single_site_doping":
        reasons.append("Doping strategy often yields useful property modifications")
    elif method == "mixed_parent":
        reasons.append("Combines elements from two distinct material families")
    elif method == "cross_substitution":
        reasons.append("Cross-substitution may preserve structure while changing properties")
    return reasons if reasons else ["Compositionally distinct from parents"]


def _risks(c):
    """Identify risks and uncertainties for a candidate."""
    risks = ["No stability calculation performed"]
    if len(c["elements"]) >= 4:
        risks.append("Complex composition — synthesis may be difficult")
    scores = c.get("scores", {})
    if scores.get("rarity_score", 0) >= 0.8:
        risks.append("Contains very rare elements — cost may be prohibitive")
    risks.append("Crystal structure unknown — may not form a stable phase")
    return risks


def _next_step(c):
    """Recommend the logical next step for this candidate."""
    if c.get("composite_score", 0) >= 0.7:
        return "Priority: Run DFT structure relaxation and stability check"
    elif c.get("composite_score", 0) >= 0.5:
        return "Evaluate with ML surrogate model (formation energy + band gap)"
    else:
        return "Low priority — consider only if specific property target matches"
